#!/usr/bin/env bash
#
# Verifica que un data package cumple con el protocolo de GECI

# ARGUMENTOS:
NOMBRE=${0##*/}
DATAPACKAGE_DIRECTORY=${1}
OPCIONES_FRICTIONLESS=${@:2}

# CONSTANTES:
DIR0=$PWD

# VARIABLES:
ERROR=0

# FUNCIONES:
function get_help {
  echo "$NOMBRE verifica que un data package cumple con el protocolo de GECI."
  echo
  echo "Opciones:"
  echo "  -h, --help     Despliega este mensaje de ayuda"
  echo "  -v, --version  Muestra la versión de $NOMBRE"
  echo
}

function get_version {
  echo "$NOMBRE v0.1.0+$(md5sum $0 | cut --characters=1-4)"
}

function validate {
  # Despliega la ruta del data package
  echo
  echo "---"
  cd $DATAPACKAGE_DIRECTORY
  pwd

  # Valida el data package
  frictionless validate $OPCIONES_FRICTIONLESS datapackage.json
  ERROR=$(($ERROR+$?))
  jsonschema --instance datapackage.json ${HOME}/.schemas/tabular-data-package.json
  ERROR=$(($ERROR+$?))
  jsonschema --instance datapackage.json ${HOME}/.schemas/protocolo-geci.json
  ERROR=$(($ERROR+$?))
  cd $DIR0
  echo "..."
  exit $ERROR
}

# MAIN:
if [[ $# == 0 ]]; then
  validate
fi

if [[ $# == 1 ]]; then
  case "$1" in
    -h | --help ) get_help ;;
    -v | --version ) get_version ;;
    * ) validate ;;
  esac
fi

if [[ $# > 1 ]]; then
  validate
fi
