#!/usr/bin/env bash
#
# Usa check-jsonschema para verificar la estructura de analyses.json

INSTANCE=${1:-analyses.json}
check-jsonschema --schemafile "${HOME}/.schemas/analyses-schema.json" "${INSTANCE}"
