name: Tests
on: [push, pull_request]

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/misctools .
    - name: Ejecuta pruebas
      run: docker run islasgeci/misctools make tests
