name: Conservación de Islas
on: [push, pull_request]

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci .
    - name: Ejecuta pruebas
      run: docker run --volume ${PWD}:/workdir islasgeci make tests
